# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/1.0.0/tag_publish/schema.json

docker:
  images:
    - name: camptocamp/python-action
dispatch:
  - {}
transformers:
  branch_to_version:
    - to: latest

      from_re: master
