checks:
  required_workflows:
    clean.yaml: False
    audit.yaml: False
    backport.yaml: False
    codeql.yaml: False

version:
  branch_to_version_re:
    - from: master
      to: latest

publish:
  pypi:
    packages: []
