name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Backport closed pull request
    timeout-minutes: 5

    steps:
      - uses: syndesisio/backport-action@master
